on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Publish to 763
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROFILE_763_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROFILE_763_SECRET_ACCESS_KEY_ID }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        with:
          registries: ${{ secrets.AWS_PROFILE_763 }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Hash
        run: echo $GITHUB_SHA

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sample-app-task
          IMAGE_TAG: latest
          INTEGRATIONS_FEED_URL: https://manage.fusebit.io/feed/integrationsFeed.json
        run: |
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} --build-arg VH=${GITHUB_SHA} --build-arg INTEGRATIONS_FEED_URL=${INTEGRATIONS_FEED_URL} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          aws ecs update-service --cluster sample-app-task --service sample-app-task --force-new-deployment
